name: Deploy to Azure Web App

# Trigger the workflow on push to 'main' branch
on:
  push:
    branches:
      - main

# Define the jobs in the workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js (if you're deploying a Node.js app)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies (if you're using Node.js)
    - name: Install dependencies
      run: npm install

    # Run tests (optional)
    - name: Run tests
      run: npm test

    # Log in to Azure using the Azure credentials stored in GitHub Secrets
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy the app to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YOUR_AZURE_APP_NAME'       # Replace with your Azure Web App name
        slot-name: 'production'               # Use 'production' for the default slot or other if you use deployment slots
        package: '.'                           # Specify the directory where your app code is located
